# Generated by Django 5.0.3 on 2024-05-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Bracelets', 'Bracelets'), ('Necklaces', 'Necklaces'), ('Earrings', 'Earrings'), ('Rings', 'Rings'), ('Watches', 'Watches'), ('Brooches', 'Brooches'), ('Anklets', 'Anklets'), ('Hair Jewelry', 'Hair Jewelry'), ('Cufflinks', 'Cufflinks'), ('Pendants', 'Pendants'), ('Charms', 'Charms'), ('Body Jewelry', 'Body Jewelry')], max_length=20)),
                ('images', models.ManyToManyField(to='catalog_app.productresource')),
            ],
        ),
    ]
